-- MySQL Script generated by MySQL Workbench
-- Sat May  4 18:11:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Loja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Loja` ;
USE `Loja` ;

-- -----------------------------------------------------
-- Table `Loja`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Loja`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `sigla` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idEstado`));


-- -----------------------------------------------------
-- Table `Loja`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Loja`.`Municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`),
  INDEX (`idEstado` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`idEstado`)
    REFERENCES `Loja`.`Estado` (`idEstado`));


-- -----------------------------------------------------
-- Table `Loja`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Loja`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `idMunicipio` INT NOT NULL,
  UNIQUE INDEX (`cpf` ASC) VISIBLE,
  PRIMARY KEY (`idCliente`),
  INDEX (`idMunicipio` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `Loja`.`Municipio` (`idMunicipio`));


-- -----------------------------------------------------
-- Table `Loja`.`ContaReceber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Loja`.`ContaReceber` (
  `idContaReceber` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `dataVencimento` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `situacao` ENUM('1', '2', '3') NOT NULL,
  PRIMARY KEY (`idContaReceber`),
  INDEX (`idCliente` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`idCliente`)
    REFERENCES `Loja`.`Cliente` (`idCliente`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
